CREATE TABLE IF NOT EXISTS pet (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    idade INT NOT NULL,
    dataNascimento DATE,
    sexo VARCHAR(20)
    );

INSERT INTO pet (nome, idade, dataNascimento, sexo)
VALUES ('Happy', 10, 22/11/1990, MACHO);